#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
R_FC Group from event-summary CSV files.

Input
-----
One or more dfc_features_summary.csv files generated by the DFC synthesis
pipeline. Required feature columns are:
    - N_DFC_event
    - DFC_event_mean_h

Output
------
dfc_features_with_clusters.csv
    Original event-summary rows plus:
    - monthly_cluster
    - monthly_cluster_name

Cluster definition
------------------
K-means clustering is performed using N_DFC_event and DFC_event_mean_h after
excluding rows with N_DFC_event <= 0 from model fitting. Rows with N_DFC_event <= 0
remain in the output with missing cluster labels.

Cluster IDs are semantically relabeled as:
    0: Minimal R_FC
    1: Frequent R_FC
    2: Long R_FC

The semantic relabeling rule is deterministic:
    - Long R_FC: cluster with the largest centroid DFC_event_mean_h
    - Frequent R_FC: among the remaining clusters, the cluster with the larger
      centroid N_DFC_event
    - Minimal R_FC: the remaining cluster
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path
from typing import Iterable

import numpy as np
import pandas as pd
from sklearn.cluster import KMeans

# Optional Windows thread control. This reduces occasional MKL/OpenMP warnings.
os.environ.setdefault("OMP_NUM_THREADS", "4")
os.environ.setdefault("LOKY_MAX_CPU_COUNT", "8")

# -----------------------------------------------------------------------------
# Direct-run settings
# -----------------------------------------------------------------------------
# Fill these paths and press Run in PyCharm/VS Code. Command-line arguments also
# work and override this block when provided.
INPUT_SUMMARIES: list[tuple[str, str]] = [   ("EV6", r"G:\\공유 드라이브\\BSG_DFC_result\\EV6\\DFC_완충후이동주차\\dfc_features_summary.csv"),
                                             ("Ioniq5", r"G:\\공유 드라이브\\BSG_DFC_result\\Ioniq5\\DFC_완충후이동주차\\dfc_features_summary.csv")
    # Example:
    # ("EV6", r"G:\\공유 드라이브\\BSG_DFC_result\\EV6\\DFC_완충후이동주차\\dfc_features_summary.csv"),
    # ("Ioniq5", r"G:\\공유 드라이브\\BSG_DFC_result\\Ioniq5\\DFC_완충후이동주차\\dfc_features_summary.csv"),
]
OUTPUT_DIR = r"C:\Users\junny\Downloads"  # Folder where dfc_features_with_clusters.csv will be saved.

# -----------------------------------------------------------------------------
# Classification settings
# -----------------------------------------------------------------------------
N_COL = "N_DFC_event"
MEAN_COL = "DFC_event_mean_h"
CLUSTER_COL = "monthly_cluster"
CLUSTER_NAME_COL = "monthly_cluster_name"

K = 3
RANDOM_STATE = 42
N_AXIS_WEIGHT = 1.2
MEAN_CAP_PERCENTILE = 99.9

CLUSTER_ID_TO_NAME = {
    0: "Minimal R_FC",
    1: "Frequent R_FC",
    2: "Long R_FC",
}

OUTPUT_FILENAME = "dfc_features_with_clusters.csv"


# -----------------------------------------------------------------------------
# I/O utilities
# -----------------------------------------------------------------------------
def load_event_summaries(summary_inputs: list[tuple[str, str | Path]]) -> pd.DataFrame:
    """Load one or more event-summary CSV files and add vehicle_model metadata."""
    if not summary_inputs:
        raise ValueError("No input summary files were provided.")

    frames: list[pd.DataFrame] = []
    for vehicle_model, path in summary_inputs:
        path = Path(path)
        if not path.exists():
            raise FileNotFoundError(f"Summary CSV not found: {path}")

        df_i = pd.read_csv(path)
        df_i = df_i.copy()
        if "vehicle_model" not in df_i.columns:
            df_i["vehicle_model"] = vehicle_model
        frames.append(df_i)

    return pd.concat(frames, axis=0, ignore_index=True, sort=False)


def require_columns(df: pd.DataFrame, columns: list[str]) -> None:
    """Raise an informative error if required columns are missing."""
    missing = [col for col in columns if col not in df.columns]
    if missing:
        raise ValueError(f"Missing required column(s): {missing}")


# -----------------------------------------------------------------------------
# Clustering utilities
# -----------------------------------------------------------------------------
def winsorize_upper(values: pd.Series, percentile: float) -> tuple[pd.Series, float]:
    """Cap upper-tail values at a percentile and return capped series and cap."""
    numeric = pd.to_numeric(values, errors="coerce").astype(float)
    cap = float(np.nanpercentile(numeric.to_numpy(dtype=float), percentile))
    return numeric.clip(upper=cap), cap


def semantic_relabel(raw_labels: np.ndarray, centers_original: np.ndarray) -> tuple[np.ndarray, dict[int, int]]:
    """Relabel K-means raw labels to stable semantic cluster IDs.

    Returns
    -------
    labels : np.ndarray
        Semantic labels where 0=Minimal R_FC, 1=Frequent R_FC, 2=Long R_FC.
    relabel_map : dict[int, int]
        Mapping from raw K-means label to semantic label.
    """
    raw_ids = sorted(int(x) for x in np.unique(raw_labels))
    if len(raw_ids) != 3:
        # This should not happen when K=3 and enough samples exist, but keep a
        # safe fallback for completeness.
        relabel_map = {raw_id: raw_id for raw_id in raw_ids}
        return raw_labels.astype(int), relabel_map

    centers = pd.DataFrame(
        centers_original,
        columns=[N_COL, MEAN_COL],
        index=raw_ids,
    )

    long_raw = int(centers[MEAN_COL].idxmax())
    remaining = [raw_id for raw_id in raw_ids if raw_id != long_raw]
    frequent_raw = int(centers.loc[remaining, N_COL].idxmax())
    minimal_raw = [raw_id for raw_id in remaining if raw_id != frequent_raw][0]

    relabel_map = {
        minimal_raw: 0,
        frequent_raw: 1,
        long_raw: 2,
    }
    labels = np.array([relabel_map[int(label)] for label in raw_labels], dtype=int)
    return labels, relabel_map


def classify_event_summary(df: pd.DataFrame) -> pd.DataFrame:
    """Classify monthly records into Minimal/Frequent/Long R_FC groups.

    Rows with N_DFC_event <= 0 or nonfinite feature values are retained in the
    output but excluded from K-means fitting and assigned missing cluster labels.
    """
    require_columns(df, [N_COL, MEAN_COL])

    out = df.copy()
    out[CLUSTER_COL] = pd.NA
    out[CLUSTER_NAME_COL] = pd.NA

    n_values = pd.to_numeric(out[N_COL], errors="coerce")
    mean_values = pd.to_numeric(out[MEAN_COL], errors="coerce")
    used_mask = (n_values > 0) & np.isfinite(n_values) & np.isfinite(mean_values)
    used_idx = out.index[used_mask]

    if len(used_idx) < K:
        print(f"[WARN] Fewer than {K} valid rows; clustering skipped.")
        return out

    work = pd.DataFrame(
        {
            N_COL: n_values.loc[used_idx].astype(float),
            MEAN_COL: mean_values.loc[used_idx].astype(float),
        },
        index=used_idx,
    )

    # Use winsorized mean only for robust clustering. The original event-summary
    # values are preserved in the output CSV.
    mean_w, cap = winsorize_upper(work[MEAN_COL], MEAN_CAP_PERCENTILE)
    work_for_fit = work.copy()
    work_for_fit[MEAN_COL] = mean_w

    x = work_for_fit[[N_COL, MEAN_COL]].to_numpy(dtype=float)
    x_weighted = x.copy()
    x_weighted[:, 0] *= N_AXIS_WEIGHT

    model = KMeans(n_clusters=K, n_init=10, random_state=RANDOM_STATE)
    raw_labels = model.fit_predict(x_weighted)

    centers_weighted = model.cluster_centers_.copy()
    centers_original = centers_weighted.copy()
    centers_original[:, 0] /= N_AXIS_WEIGHT

    labels, relabel_map = semantic_relabel(raw_labels, centers_original)

    out.loc[used_idx, CLUSTER_COL] = labels
    out.loc[used_idx, CLUSTER_NAME_COL] = [CLUSTER_ID_TO_NAME[int(label)] for label in labels]

    print("[INFO] Monthly DFC-event classification complete")
    print(f"       total rows              : {len(out)}")
    print(f"       rows used for clustering: {len(used_idx)}")
    print(f"       rows with N_DFC_event=0 : {int((n_values <= 0).sum())}")
    print(f"       mean cap @{MEAN_CAP_PERCENTILE}%       : {cap:.6g} h")
    print(f"       N-axis weight           : {N_AXIS_WEIGHT}")
    print(f"       raw-to-semantic relabel : {relabel_map}")

    counts = pd.Series(labels).value_counts().sort_index()
    for cluster_id, count in counts.items():
        print(f"       {cluster_id} ({CLUSTER_ID_TO_NAME[int(cluster_id)]}): {int(count)}")

    return out


def run_classification(summary_inputs: list[tuple[str, str | Path]], output_dir: str | Path) -> Path:
    """Load event summaries, classify monthly records, and save one output CSV."""
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    summary = load_event_summaries(summary_inputs)
    classified = classify_event_summary(summary)

    output_path = output_dir / OUTPUT_FILENAME
    classified.to_csv(output_path, index=False, encoding="utf-8-sig")
    print(f"[SAVE] {output_path}")
    return output_path


# -----------------------------------------------------------------------------
# CLI
# -----------------------------------------------------------------------------
def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Classify monthly DFC-event summary records into R_FC groups."
    )
    parser.add_argument(
        "--input",
        nargs="+",
        default=None,
        help="One or more dfc_features_summary.csv paths.",
    )
    parser.add_argument(
        "--labels",
        nargs="*",
        default=None,
        help="Optional labels for input summaries, e.g., EV6 Ioniq5.",
    )
    parser.add_argument(
        "--output-dir",
        default=None,
        help="Folder where dfc_features_with_clusters.csv will be saved.",
    )
    return parser


def main(argv: Iterable[str] | None = None) -> None:
    parser = build_arg_parser()

    if argv is None:
        import sys
        argv = sys.argv[1:]

    argv = list(argv)

    # Direct-run mode.
    if len(argv) == 0:
        if not INPUT_SUMMARIES or not OUTPUT_DIR:
            parser.error("Fill INPUT_SUMMARIES/OUTPUT_DIR or provide --input and --output-dir.")
        run_classification(INPUT_SUMMARIES, OUTPUT_DIR)
        return

    args = parser.parse_args(argv)
    if not args.input or not args.output_dir:
        parser.error("--input and --output-dir are required.")

    if args.labels:
        if len(args.labels) != len(args.input):
            parser.error("The number of --labels must match the number of --input files.")
        summary_inputs = list(zip(args.labels, args.input))
    else:
        summary_inputs = [(Path(path).stem, path) for path in args.input]

    run_classification(summary_inputs, args.output_dir)


if __name__ == "__main__":
    main()
